# Generated by Django 4.1.4 on 2023-01-31 09:53

import apps.workshop.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('image_name', models.ImageField(upload_to=apps.workshop.models.upload_workShop_images, verbose_name='عکس اصلی')),
                ('date_time', models.DateTimeField(verbose_name='تاریخ و زمان برگزاری')),
                ('place', models.CharField(max_length=150, verbose_name='مکان برگزاری')),
                ('teacher', models.CharField(max_length=150, verbose_name='مدرس')),
                ('information', models.TextField(verbose_name='اطلاعات')),
                ('report_text', models.TextField(blank=True, null=True, verbose_name='متن گزارش')),
                ('viewNumber', models.IntegerField(default=0, verbose_name='تعداد بازدید')),
                ('register_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ ثبت')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیر فعال')),
            ],
            options={
                'verbose_name': 'کارگاه',
                'verbose_name_plural': 'کارگاه ها',
                'db_table': 't_workshop',
            },
        ),
        migrations.CreateModel(
            name='WorkShopStatus',
            fields=[
                ('status_code', models.IntegerField(primary_key=True, serialize=False, verbose_name='کد وضعیت')),
                ('status_title', models.CharField(max_length=100, verbose_name='عنوان وضعیت')),
            ],
            options={
                'verbose_name': 'وضعیت کارگاه',
                'verbose_name_plural': 'وضعیت کارگاه ها',
                'db_table': 't_workshop_status',
            },
        ),
        migrations.CreateModel(
            name='WorkShop_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.workshop.models.upload_workShop_gallery, verbose_name='تصویر')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.workshop', verbose_name='کارگاه')),
            ],
            options={
                'verbose_name': 'گالری کارگاه',
                'verbose_name_plural': 'گالری کارگاه ها',
                'db_table': 't_workshop_gallery',
            },
        ),
        migrations.AddField(
            model_name='workshop',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.workshopstatus', verbose_name='وضعیت کارگاه'),
        ),
    ]
