# Generated by Django 4.1.4 on 2023-01-02 18:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='عنوان مقاله')),
                ('image', models.ImageField(upload_to='images/articles/', verbose_name='تصویر اصلی مقاله')),
                ('short_text', models.TextField(verbose_name='متن خلاصه مقاله')),
                ('key_words', models.CharField(max_length=200, verbose_name='کلمات کلیدی')),
                ('register_date', models.DateField(auto_now_add=True, verbose_name='تاریخ درج مقاله')),
                ('publish_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('view_number', models.PositiveSmallIntegerField(verbose_name='تعداد بازدید')),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'db_table': 't-articles',
            },
        ),
        migrations.CreateModel(
            name='ArticleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(max_length=100, verbose_name='عنوان گروه مقالات')),
            ],
            options={
                'verbose_name': 'گروه مقالات',
                'verbose_name_plural': 'گروه های مقالات',
                'db_table': 't-article_groups',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام')),
                ('family', models.CharField(max_length=20, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='ایمیل')),
                ('mobile', models.CharField(blank=True, max_length=12, null=True, verbose_name='شماره موبایل')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسندگان',
                'db_table': 't-authors',
            },
        ),
        migrations.CreateModel(
            name='ArticleGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/articles/article-<django.db.models.fields.related.ForeignKey>/', verbose_name='تصویر')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article', verbose_name='مقاله')),
            ],
            options={
                'verbose_name': 'گالری',
                'verbose_name_plural': 'گالری ها',
                'db_table': 't-articles_gallery',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ManyToManyField(to='articles.author', verbose_name='نویسنده'),
        ),
        migrations.AddField(
            model_name='article',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.articlegroup', verbose_name='گروه مقاله'),
        ),
    ]
