# Generated by Django 4.1.4 on 2023-01-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.TextField(default='متن مقاله', verbose_name='متن مقاله'),
        ),
    ]
