# Generated by Django 4.1.4 on 2023-01-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlegallery',
            name='image',
            field=models.ImageField(upload_to='images/articles/article-False/', verbose_name='تصویر'),
        ),
    ]
