# Generated by Django 4.1.4 on 2023-01-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_articlegallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlegallery',
            name='image',
            field=models.ImageField(upload_to='images/articles/<django.db.models.fields.related.ForeignKey>/', verbose_name='تصویر'),
        ),
    ]
