# Generated by Django 4.1.4 on 2023-01-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_articlegallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlegallery',
            name='image',
            field=models.ImageField(upload_to='images/articles/-17/', verbose_name='تصویر'),
        ),
    ]
