# Generated by Django 4.1.4 on 2022-12-28 12:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=20, verbose_name='نام مکان')),
                ('information', models.TextField(default='توضیحات', verbose_name='توضیحات')),
                ('place_image', models.ImageField(upload_to='media/images/place/', verbose_name='تصویر')),
                ('visiting_day', models.CharField(max_length=20, verbose_name='روز های بازدید')),
                ('visiting_hour', models.CharField(max_length=20, verbose_name='ساعت های بازدید')),
                ('rules', models.TextField(blank=True, verbose_name='قوانین')),
                ('register_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت نام')),
            ],
            options={
                'verbose_name': 'مکان ',
                'verbose_name_plural': 'مکان ها',
                'db_table': 't_place',
            },
        ),
        migrations.CreateModel(
            name='VisitorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20, verbose_name='نوع بازدید کننده')),
            ],
            options={
                'verbose_name': 'نوع بازدید کننده ',
                'verbose_name_plural': 'نوع بازدید کننده ها',
                'db_table': 't_visitor_type',
            },
        ),
        migrations.CreateModel(
            name='TicketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place', verbose_name='مکان مورد نظر')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.visitortype', verbose_name='نوع بازدید کننده')),
            ],
            options={
                'verbose_name': 'بهای بلیت',
                'verbose_name_plural': 'بهای بلیت ها',
                'db_table': 't_ticket_prices',
            },
        ),
    ]
