# Generated by Django 4.1.4 on 2022-12-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_image',
            field=models.ImageField(upload_to='images/place/', verbose_name='تصویر'),
        ),
    ]
