# Generated by Django 4.1.4 on 2022-12-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_place_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_image',
            field=models.ImageField(upload_to='images/places/', verbose_name='تصویر'),
        ),
    ]
