# Generated by Django 4.1.4 on 2022-12-30 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_place_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=80, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=100, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='پیام')),
                ('is_seen', models.BooleanField(default=False, verbose_name='وضعیت مشاهده توسط مدیر')),
                ('register_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت پیام')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
                'db_table': 't_messages',
            },
        ),
    ]
